export enum ExceptionTypeKeys {
  BAD_MODEL = 'BadModelException',
  INVALID_PERMISSIONS = 'InvalidPermissionsException',
  NOT_FOUND = 'NotFoundException',
  UNEXPECTED = 'UnexpectedException',
}

export enum ErrorCodesKeys {
  UNIMPLEMENTED = 'TST000',

  // ...
  REPOSITORY_UNEXPECTED = 'TST010',
  TOKEN_GENERATION_FAILED = 'TST011',
  TOKEN_STORAGE_FAILED = 'TST012',

  REQUEST_NOT_VALID = 'TST020',
  ID_FORMAT_NOT_VALID = 'TST021',
  NAME_TOO_LONG = 'TST022',
  EMAIL_FORMAT_NOT_VALID = 'TST023',
  PASSWORD_TOO_SHORT = 'TST024',
  PASSWORDS_NOT_MATCH = 'TST025',
  USER_ALREADY_EXISTS = 'TST026',
  PASSWORD_INCORRECT = 'TST027',
  AUTH_HEADER_NOT_PROVIDED = 'TST028',

  USER_NOT_FOUND = 'TST030',

  TOKEN_NOT_VALID = 'TST040',
  USER_OR_TOKEN_NOT_FOUND = 'TST041',
}
